import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { verifySignedCanonicalExport } from './canonical-export.js';
import { buildCanonicalSentinelVerdict, serializeCanonicalSentinelVerdict, hashCanonicalSentinelVerdict } from './canonical-verdict.js';
import type { SentinelVerifyResponse } from './types.js';

// Frozen signed fixture generated by pre-#85 a1747ea. Public key only;
// not a live receipt or a trusted issuer identity. Do not regenerate in this test.
const fixture = JSON.parse(readFileSync(new URL('./fixtures/issue-85-legacy-export.json', import.meta.url), 'utf8'));

describe('issue #85 legacy exports and unsigned diagnostic boundary', () => {
  it('verifies the pre-change signed receipt with no diagnostic fields', () => {
    const old = fixture.response as SentinelVerifyResponse;
    expect(old.meta.promotion).not.toHaveProperty('prose_action_kind');
    expect(old.meta.promotion).not.toHaveProperty('caller_kinds_diagnostic');
    expect(verifySignedCanonicalExport(fixture.signed, fixture.publicKey)).toMatchObject({ ok: true });
    const canonical = buildCanonicalSentinelVerdict(old);
    expect(serializeCanonicalSentinelVerdict(canonical)).toBe(fixture.signed.canonical);
    expect(hashCanonicalSentinelVerdict(canonical)).toBe(fixture.signed.digest);
  });

  it('changing unsigned kind diagnostics cannot invalidate or authenticate the signed payload', () => {
    const modified = structuredClone(fixture.response) as SentinelVerifyResponse;
    Object.assign(modified.meta.promotion!, {
      prose_action_kind: 'value_transfer', prose_mandate_kind: 'unknown',
      caller_kinds_diagnostic: {
        caller_action_kind: 'permission', caller_mandate_kind: 'deploy_ship',
        caller_kinds_do_not_widen: false,
        triggering_rule: 'callerDeclaredKindsDoNotWiden',
      },
    });
    const canonical = buildCanonicalSentinelVerdict(modified);
    expect(serializeCanonicalSentinelVerdict(canonical)).toBe(fixture.signed.canonical);
    expect(hashCanonicalSentinelVerdict(canonical)).toBe(fixture.signed.digest);
    expect(verifySignedCanonicalExport(fixture.signed, fixture.publicKey)).toMatchObject({ ok: true });
    // Contrast: modifying the actual signed payload must fail verification.
    expect(verifySignedCanonicalExport({
      ...fixture.signed,
      canonical: fixture.signed.canonical.replace('"ALLOW"', '"BLOCK"'),
    }, fixture.publicKey)).toMatchObject({ ok: false, code: 'signature_invalid' });
  });
});
